import type { Metadata } from "next";
import "./globals.css";
import { Inter, Nunito } from 'next/font/google'
//import localFont from "next/font/local";

const font = Nunito({
  subsets: ['latin'],
  display: 'swap',
})
 

/* Using local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Guessing that it takes all the children in the pages and turns the font to specified
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}> 
      <body>{children}</body>
    </html>
  );
}
